-- SQLite
-- CREATE TABLES

CREATE TABLE GAME_OUTPUT(
    GAME_OUTPUT_ID INTEGER PRIMARY KEY,
    GAME_OUTPUT_NAME VARCHAR(255));

-- CREATE TABLE STATEMENT();

CREATE TABLE GAME(
    GAME_ID INTEGER PRIMARY KEY, 
    FOREIGN KEY(GAME_OUTPUT_ID) REFERENCES GAME_OUTPUT(GAME_OUTPUT_ID));
    -- FOREIGN KEY(LAST_STATEMENT_ID) REFERENCES STATEMENT(STATEMENT_ID), 
    -- IS_EXPECTING_CLARIFIED_STATEMENT BOOLEAN);

CREATE TABLE GAME_OBJECT(
    GAME_OBJECT_ID INTEGER PRIMARY KEY,
    FOREIGN KEY(GAME_ID) REFERENCES GAME(GAME_ID),
    GAME_OBJECT_NAME VARCHAR(255),
    GAME_OBJECT_NAME VARCHAR(255),
    GAME_OBJECT_NICKNAME VARCHAR(255),
    GAME_OBJECT_HEALTH INTEGER,
    GAME_OBJECT_IS_PERMANENT_FIXTURE BOOLEAN,
    GAME_OBJECT_IS_DESTROYED BOOLEAN);

CREATE TABLE CONTAINER(
    CONTAINER_ID INTEGER PRIMARY KEY,
    FOREIGN KEY(GAME_OBJECT_ID) REFERENCES GAME_OBJECT(GAME_OBJECT_ID),
    CONTAINER_IS_OPEN BOOLEAN,
    CONTAINER_ITEM_LIMIT INTEGER);

CREATE TABLE GAME_OBJECT_IN_CONTAINER(
    FOREIGN KEY(GAME_OBJECT_ID) REFERENCES GAME_OBJECT(GAME_OBJECT_ID),
    FOREIGN KEY(CONTAINER_OBJECT_ID) REFERENCES CONTAINER_OBJECT(CONTAINER_OBJECT_ID);

CREATE TABLE PLAYER(
    PLAYER_ID INTEGER PRIMARY KEY,
    FOREIGN KEY(GAME_OBJECT_ID) REFERENCES GAME_OBJECT(GAME_OBJECT_ID);

CREATE TABLE ROOM(
    ROOM_ID INTEGER PRIMARY KEY,
    FOREIGN KEY(GAME_OBJECT_ID) REFERENCES GAME_OBJECT(GAME_OBJECT_ID));
